---
- name: Zabbix SLA Multi-Report
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    report_out: "/runner/artifacts/{{ awx_job_id }}/sla_multi_report.xlsx"
    sla_codes_path: "/runner/artifacts/{{ awx_job_id }}/sla_codes.yml"

  tasks:
    - name: Write SLA codes file
      copy:
        dest: "{{ sla_codes_path }}"
        mode: "0644"
        content: |
          sla_report_codes:
            - code: egw.net
              name: Gateway/Router (EGW)
            - code: eap.svr
              name: Application Server (EAP)
            - code: ebk.svr
              name: Backup Server (EBK)
            - code: ecs.net
              name: Camera Security (ECS)
            - code: edb.svr
              name: Database Server (EDB)
            - code: ela.ows
              name: Enterprise Laptop (ELA)
            - code: efs.svr
              name: File Server (EFS)
            - code: egw.net
              name: Gateway/Router (EGW)
            - code: ens.sto
              name: Network Attached Storage (ENS)
            - code: esc.net
              name: Network Switch - Core (ESC)
            - code: ewe.net
              name: Network Switch - Edge (EWE)
            - code: san.sto
              name: Storage Area Network (SAN)
            - code: eps.ups
              name: Uninterruptible Power Supply (EPS)
            - code: evc.svr
              name: Virtualization Controler (EVC)
            - code: evh.phy
              name: Virtualization Host (EVH)
            - code: wae.aps
              name: Wireless Access Equipment (WAE)
            - code: wap.aps
              name: Wireless Access Point (WAP)
            - code: wpt.aps
              name: Wireless Point to Point (WPT)

    - name: Run uptime report script (multi-sheet)
      environment:
        ZABBIX_API_URL: "{{ lookup('env', 'ZABBIX_API_URL') }}"
        ZABBIX_API_TOKEN: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
        REPORT_OUTPUT: "{{ report_out }}"
        SLA_CODES_FILE: "{{ sla_codes_path }}"
        TAG_KEY: "{{ lookup('env', 'TAG_KEY') | default('device', true) }}"
        DAYS: "{{ lookup('env', 'DAYS') | default('30', true) }}"
      command: python3 zabbix_uptime_report.py

    - name: Email the report
      community.general.mail:
        host: smtp.timberlinkaustralia.com.au
        port: 25
        to: "{{ (email_recipients | default(email_recipients_default) | default([])) | join(', ') }}"
        from: awx@timberlinkaustralia.com.au
        subject: "SLA Multi-Report ({{ ansible_date_time.date }})"
        body: "Attached is the latest multi-sheet SLA report."
        attach:
          - "{{ report_out }}"
