---
- name: Zabbix SLA Multi-Report (NetBox-driven)
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - netbox.netbox

  vars:
    report_out: "/runner/artifacts/{{ awx_job_id }}/sla_multi_report.xlsx"
    sla_codes_path: "/runner/artifacts/{{ awx_job_id }}/sla_codes.yml"

  pre_tasks:
    - name: Resolve NetBox API endpoint/token from vars or env (credential)
      set_fact:
        netbox_api: "{{ NETBOX_API | default(lookup('env','NETBOX_API'), true) }}"
        netbox_token: "{{ NETBOX_TOKEN | default(lookup('env','NETBOX_TOKEN'), true) }}"

    - name: Assert NetBox creds are present
      assert:
        that:
          - (netbox_api | length) > 0
          - (netbox_token | length) > 0
        fail_msg: "NETBOX_API / NETBOX_TOKEN are required (via vars or injected env)."

  tasks:
    - name: Pull device roles with cf_sla_report_req == true from NetBox
      set_fact:
        nb_roles: >-
          {{ query('netbox.netbox.nb_lookup',
                   'dcim.device_roles',
                   api_endpoint=netbox_api,
                   token=netbox_token,
                   api_filter='cf_sla_report_req=True') }}

    - name: Build SLA entries (code + name) from NetBox roles
      set_fact:
        sla_entries: "{{ (sla_entries | default([])) + [ {
            'code': ((item.custom_fields.cf_sla_report_code | default(item.slug)) | string),
            'name': (item.name | string)
          } ] }}"
      loop: "{{ nb_roles }}"
      when:
        - item is mapping
        - item.custom_fields is defined
        - (item.custom_fields.cf_sla_report_req | default(false)) | bool

    - name: Fail if no SLA entries found
      fail:
        msg: "No device roles meet cf_sla_report_req=True (nothing to report)."
      when: sla_entries | default([]) | length == 0

    - name: Write SLA codes file for the report script
      copy:
        dest: "{{ sla_codes_path }}"
        mode: "0644"
        content: "{{ {'sla_report_codes': sla_entries} | to_nice_yaml(indent=2) }}"

    - name: Run uptime report script (multi-sheet; SLA list comes from NetBox)
      environment:
        ZABBIX_API_URL: "{{ ZABBIX_API_URL }}"
        ZABBIX_API_TOKEN: "{{ ZABBIX_API_TOKEN }}"
        REPORT_OUTPUT: "{{ report_out }}"
        SLA_CODES_FILE: "{{ sla_codes_path }}"
        TAG_KEY: "{{ TAG_KEY | default('device') }}"
        DAYS: "{{ DAYS | default('30') }}"
      command: python3 zabbix_uptime_report.py

    - name: Email the report
      community.general.mail:
        host: smtp.timberlinkaustralia.com.au
        port: 25
        to: "{{ (email_recipients | default(email_recipients_default) | default([])) | join(', ') }}"
        from: awx@timberlinkaustralia.com.au
        subject: "SLA Multi-Report ({{ lookup('pipe','date +%Y-%m-%d') }})"
        body: "Attached is the latest multi-sheet SLA report (NetBox-driven)."
        attach:
          - "{{ report_out }}"
