---
- name: Zabbix EGW.NET Uptime Report
  hosts: localhost
  gather_facts: false
  connection: local 
  tasks:
    - name: Run uptime report script
      command: python3 zabbix_uptime_report.py
      environment:
        ZABBIX_API_URL: "{{ lookup('env', 'ZABBIX_API_URL') }}"
        ZABBIX_API_TOKEN: "{{ lookup('env', 'ZABBIX_API_TOKEN') }}"
        REPORT_OUTPUT: "/tmp/egw_net_zabbix_report.csv"

    - name: Email the report
      community.general.mail:
        host: smtp.timberlinkaustralia.com.au    
        port: 25               
        to: "{{ (email_recipients | default(email_recipients_default))
            | join(', ') }}"        
        from: awx@timberlinkaustralia.com.au       
        subject: "EGW.NET Zabbix 30-Day Uptime Report"
        body: "Attached is the latest Uptime Report."
        attach:
          - "/tmp/egw_net_zabbix_report.csv"